[package]
name = "remnantsofsiren/scoresync"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["test", "Packages", "build", "test.project.json", "selene.toml", "README.md", ".gitignore", ".vscode"]
description = """
    ScoreSync aims to fix some outstanding issues found when making Leaderboards

    Api Page: https://remnantsofsiren.github.io/ScoreSync
"""

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Sift = "csqrl/sift@0.0.9"
Signal = "data-oriented-house/lemonsignal@1.10.0"
Promise = "evaera/promise@4.0.0"